# Generated by Django 3.0.2 on 2020-02-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('trading', '0003_auto_20200209_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Binder')),
            ],
        ),
        migrations.CreateModel(
            name='Have',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Binder')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
            ],
        ),
    ]
