# Generated by Django 3.0.2 on 2020-02-10 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('trading', '0004_have_want'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='oracle_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='want',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Set'),
        ),
    ]
