# Generated by Django 3.0.2 on 2020-02-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('num_cards', models.IntegerField()),
                ('block_code', models.CharField(max_length=10, null=True)),
                ('block_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('oracle_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('cmc', models.DecimalField(decimal_places=3, max_digits=10)),
                ('type_line', models.CharField(max_length=200)),
                ('oracle_text', models.TextField(null=True)),
                ('flavor_text', models.TextField(null=True)),
                ('power', models.CharField(max_length=10, null=True)),
                ('toughness', models.CharField(max_length=10, null=True)),
                ('reserved', models.BooleanField()),
                ('foil', models.BooleanField()),
                ('nonfoil', models.BooleanField()),
                ('promo', models.BooleanField()),
                ('reprint', models.BooleanField()),
                ('collector_number', models.CharField(max_length=10)),
                ('artist', models.CharField(max_length=200, null=True)),
                ('loyalty', models.CharField(max_length=10, null=True)),
                ('mana_cost', models.CharField(max_length=200, null=True)),
                ('white_identy', models.BooleanField(default=False)),
                ('blue_identity', models.BooleanField(default=False)),
                ('black_identity', models.BooleanField(default=False)),
                ('red_identity', models.BooleanField(default=False)),
                ('green_identity', models.BooleanField(default=False)),
                ('rarity', models.CharField(choices=[('c', 'common'), ('u', 'uncommon'), ('r', 'rare'), ('m', 'mythic')], max_length=1)),
                ('language', models.CharField(max_length=10)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Set')),
            ],
        ),
    ]
